[[_sec_declarative_package_mgmt]]
= Declarative Package Management


With declarative package management, you specify which packages you want on your system by setting the option <<_opt_environment.systempackages>>.
For instance, adding the following line to [path]``configuration.nix``
 enables the Mozilla Thunderbird email application: 
[source]
----

 = [ pkgs.thunderbird ];
----

The effect of this specification is that the Thunderbird package from Nixpkgs will be built or downloaded as part of the system when you run [command]``nixos-rebuild switch``. 

[NOTE]
====
Some packages require additional global configuration such as D-Bus or systemd service registration so adding them to <<_opt_environment.systempackages>> might not be sufficient.
You are advised to check the link:#ch-options[list of options] whether a NixOS module for the package does not exist. 
====


You can get a list of the available packages as follows: 
----

$ nix-env -qaP '*' --description
nixos.firefox   firefox-23.0   Mozilla Firefox - the browser, reloaded`...`
----

The first column in the output is the __attribute name__, such as ``nixos.thunderbird``. 

Note: the `nixos` prefix tells us that we want to get the package from the `nixos` channel and works only in CLI tools.
In declarative configuration use `pkgs` prefix (variable). 

To "`uninstall`" a package, simply remove it from <<_opt_environment.systempackages>> and run [command]``nixos-rebuild switch``. 

include::customizing-packages.adoc[leveloffset=1]


include::adding-custom-packages.adoc[leveloffset=1]
