[[_ch_file_systems]]
= File Systems
:doctype: book
:sectnums:
:toc: left
:icons: font
:experimental:
:sourcedir: .
:imagesdir: ./images


You can define file systems using the [option]``fileSystems`` configuration option.
For instance, the following definition causes NixOS to mount the Ext4 file system on device [path]``/dev/disk/by-label/data``
 onto the mount point [path]``/data``
: 
[source]
----

."/data" =
  { device = "/dev/disk/by-label/data";
    fsType = "ext4";
  };
----

Mount points are created automatically if they don`'t already exist.
For [option]``<<_opt_filesystems._name__.device,device>>``, it`'s best to use the topology-independent device aliases in [path]``/dev/disk/by-label``
 and [path]``/dev/disk/by-uuid``
, as these don`'t change if the topology changes (e.g.
if a disk is moved to another IDE controller). 

You can usually omit the file system type ([option]``<<_opt_filesystems._name__.fstype,fsType>>``), since [command]``mount`` can usually detect the type and load the necessary kernel module automatically.
However, if the file system is needed at early boot (in the initial ramdisk) and is not ``ext2``, `ext3` or ``ext4``, then it`'s best to specify [option]``fsType`` to ensure that the kernel module is available. 

[NOTE]
====
System startup will fail if any of the filesystems fails to mount, dropping you to the emergency shell.
You can make a mount asynchronous and non-critical by adding ``<<_opt_filesystems._name__.options,options>> = [
   "nofail" ];``. 
====

include::luks-file-systems.adoc[leveloffset=1]
