[[_sec_xfce]]
= Xfce Desktop Environment
:doctype: book
:sectnums:
:toc: left
:icons: font
:experimental:
:sourcedir: .
:imagesdir: ./images


To enable the Xfce Desktop Environment, set 
[source]
----

 = true;
 = "xfce";
----

Optionally, _picom_ can be enabled for nice graphical effects, some example settings: 
[source]
----

services.picom = {
  enable          = true;
  fade            = true;
  inactiveOpacity = "0.9";
  shadow          = true;
  fadeDelta       = 4;
};
----

Some Xfce programs are not installed automatically.
To install them manually (system wide), put them into your <<_opt_environment.systempackages>> from ``pkgs.xfce``. 

[[_sec_xfce_thunar_plugins]]
== Thunar Plugins


If you'd like to add extra plugins to Thunar, add them to <<_opt_services.xserver.desktopmanager.xfce.thunarplugins>>.
You shouldn't just add them to <<_opt_environment.systempackages>>. 

[[_sec_xfce_troubleshooting]]
== Troubleshooting


Even after enabling udisks2, volume management might not work.
Thunar and/or the desktop takes time to show up.
Thunar will spit out this kind of message on start (look at [command]``journalctl --user -b``). 
[source]
----

Thunar:2410): GVFS-RemoteVolumeMonitor-WARNING **: remote volume monitor with dbus name org.gtk.Private.UDisks2VolumeMonitor is not supported
----

This is caused by some needed GNOME services not running.
This is all fixed by enabling "Launch GNOME services on startup" in the Advanced tab of the Session and Startup settings panel.
Alternatively, you can run this command to do the same thing. 
[source]
----

$ xfconf-query -c xfce4-session -p /compat/LaunchGNOME -s true
----

A log-out and re-log will be needed for this to take effect. 