= nixos-version(8)
:doctype: manpage
:manvolnum: 8
:manmanual: nixos-version
:mansource: NixOS

== NAME

nixos-version - show the NixOS version

== SYNOPSIS

[--hash] [--revision] [--json] 


  
== Description

   This command shows the version of the currently active NixOS configuration.
   For example:

     `_16.03`_
     
       The NixOS release, indicating the year and month in which it was
       released (e.g. March 2016).
      
    
     `_1011`_
     
       The number of commits in the Nixpkgs Git repository between the start of
       the release branch and the commit from which this version was built.
       This ensures that NixOS versions are monotonically increasing. It is
       `git` when the current NixOS configuration was built
       from a checkout of the Nixpkgs Git repository rather than from a NixOS
       channel.
      
    
     `_6317da4`_
     
       The first 7 characters of the commit in the Nixpkgs Git repository from
       which this version was built.
      
    
     `_Emu`_
     
       The code name of the NixOS release. The first letter of the code name
       indicates that this is the N'th stable NixOS release; for example, Emu
       is the fifth release.
      
   



  
== Options

   This command accepts the following options:
  


    *--hash*
    *--revision*
    
      Show the full SHA1 hash of the Git commit from which this configuration
      was built, e.g.


   

    *--json*
    
      Print a JSON representation of the versions of NixOS and the
      top-level configuration flake.
     

  