[[_ch_containers]]
= Container Management
:doctype: book
:sectnums:
:toc: left
:icons: font
:experimental:
:sourcedir: .
:imagesdir: ./images


NixOS allows you to easily run other NixOS instances as __containers__.
Containers are a light-weight approach to virtualisation that runs software in the container at the same speed as in the host system.
NixOS containers share the Nix store of the host, making container creation very efficient. 

[WARNING]
====
Currently, NixOS containers are not perfectly isolated from the host system.
This means that a user with root access to the container can do things that affect the host.
So you should not give container root access to untrusted users. 
====


NixOS containers can be created in two ways: imperatively, using the command [command]``nixos-container``, and declaratively, by specifying them in your [path]``configuration.nix``
.
The declarative approach implies that containers get upgraded along with your host system when you run [command]``nixos-rebuild``, which is often not what you want.
By contrast, in the imperative approach, containers are configured and updated independently from the host system. 

include::imperative-containers.adoc[leveloffset=1]


include::declarative-containers.adoc[leveloffset=1]


include::container-networking.adoc[leveloffset=1]
