[[_chap_submitting_changes]]
= Submitting changes
:doctype: book
:sectnums:
:toc: left
:icons: font
:experimental:
:sourcedir: .
:imagesdir: ./images

[[_submitting_changes_making_patches]]
== Making patches

* Read https://nixos.org/nixpkgs/manual/[Manual (How to write packages for Nix)]. 
* Fork https://github.com/nixos/nixpkgs/[the Nixpkgs repository] on GitHub. 
* Create a branch for your future fix. 
+
** You can make branch from a commit of your local [command]``nixos-version``. That will help you to avoid additional local compilations. Because you will receive packages from binary cache. For example 
+
----

$ nixos-version --hash
0998212
$ git checkout 0998212
$ git checkout -b 'fix/pkg-name-update'
----
** Please avoid working directly on the [command]``master`` branch. 
* Make commits of logical units. 
* If you removed pkgs or made some major NixOS changes, write about it in the release notes for the next stable release. For example [command]``nixos/doc/manual/release-notes/rl-2003.xml``. 
* Check for unnecessary whitespace with [command]``git diff --check`` before committing. 
* Format the commit in a following way: 
+

[source]
----

(pkg-name | nixos/<module>): (from -> to | init at version | refactor | etc)
Additional information.
----
** Examples: 
+
*** [command]``nginx: init at 2.0.1``
*** [command]``firefox: 54.0.1 -> 55.0``
*** [command]``nixos/hydra: add bazBaz option``
*** [command]``nixos/nginx: refactor config generation``
* Test your changes. If you work with 
+
** nixpkgs: 
+
*** update pkg -> 
+
**** [command]``nix-env -i pkg-name -f <path to your local nixpkgs folder>``
*** add pkg -> 
+
**** Make sure it's in [command]``pkgs/top-level/all-packages.nix``
**** [command]``nix-env -i pkg-name -f <path to your local nixpkgs folder>``
*** __If you don't want to install pkg in you profile__. 
+
**** [command]``nix-build -A pkg-attribute-name <path to your local nixpkgs folder>/default.nix`` and check results in the folder [command]``result``. It will appear in the same directory where you did [command]``nix-build``. 
*** If you did [command]``nix-env -i pkg-name`` you can do [command]``nix-env -e pkg-name`` to uninstall it from your system. 
** NixOS and its modules: 
+
*** You can add new module to your NixOS configuration file (usually it's [command]``/etc/nixos/configuration.nix``). And do [command]``sudo nixos-rebuild test -I nixpkgs=<path to your local nixpkgs folder> --fast``. 
* If you have commits [command]``pkg-name: oh, forgot to insert whitespace``: squash commits in this case. Use [command]``git rebase -i``. 
* https://git-scm.com/book/en/v2/Git-Branching-Rebasing[Rebase] your branch against current [command]``master``. 


[[_submitting_changes_submitting_changes]]
== Submitting changes

* Push your changes to your fork of nixpkgs. 
* Create the pull request 
* Follow https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#submitting-changes[the contribution guidelines]. 


[[_submitting_changes_submitting_security_fixes]]
== Submitting security fixes


Security fixes are submitted in the same way as other changes and thus the same guidelines apply. 

If the security fix comes in the form of a patch and a CVE is available, then the name of the patch should be the CVE identifier, so e.g. `CVE-2019-13636.patch` in the case of a patch that is included in the Nixpkgs tree.
If a patch is fetched the name needs to be set as well, e.g.: 

[source]
----

   (fetchpatch {
     name = "CVE-2019-11068.patch";
     url = "https://gitlab.gnome.org/GNOME/libxslt/commit/e03553605b45c88f0b4b2980adfbbb8f6fca2fd6.patch";
     sha256 = "0pkpb4837km15zgg6h57bncp66d5lwrlvkr73h0lanywq7zrwhj8";
   })
----


If a security fix applies to both master and a stable release then, similar to regular changes, they are preferably delivered via master first and cherry-picked to the release branch. 

Critical security fixes may by-pass the staging branches and be delivered directly to release branches such as `master` and ``release-*``. 

[[_submitting_changes_pull_request_template]]
== Pull Request Template


The pull request template helps determine what steps have been made for a contribution so far, and will help guide maintainers on the status of a change.
The motivation section of the PR should include any extra details the title does not address and link any existing issues related to the pull request. 

When a PR is created, it will be pre-populated with some checkboxes detailed below: 

[[_submitting_changes_tested_with_sandbox]]
=== Tested using sandboxing


When sandbox builds are enabled, Nix will setup an isolated environment for each build process.
It is used to remove further hidden dependencies set by the build environment to improve reproducibility.
This includes access to the network during the build outside of `fetch*` functions and files outside the Nix store.
Depending on the operating system access to other resources are blocked as well (ex.
inter process communication is isolated on Linux); see https://nixos.org/nix/manual/#conf-sandbox[sandbox] in Nix manual for details. 

Sandboxing is not enabled by default in Nix due to a small performance hit on each build.
In pull requests for https://github.com/NixOS/nixpkgs/[nixpkgs] people are asked to test builds with sandboxing enabled (see `Tested using sandboxing` in the pull request template) because inhttps://nixos.org/hydra/ sandboxing is also used. 

Depending if you use NixOS or other platforms you can use one of the following methods to enable sandboxing *before* building the package: 

* **Globally enable sandboxing on NixOS**: add the following to [path]``configuration.nix``
+
----
nix.useSandbox = true;
----
* **Globally enable sandboxing on non-NixOS platforms**: add the following to: [path]``/etc/nix/nix.conf``
+
----
sandbox = true
----


[[_submitting_changes_platform_diversity]]
=== Built on platform(s)


Many Nix packages are designed to run on multiple platforms.
As such, it's important to let the maintainer know which platforms your changes have been tested on.
It's not always practical to test a change on all platforms, and is not required for a pull request to be merged.
Only check the systems you tested the build on in this section. 

[[_submitting_changes_nixos_tests]]
=== Tested via one or more NixOS test(s) if existing and applicable for the change (look inside nixos/tests)


Packages with automated tests are much more likely to be merged in a timely fashion because it doesn't require as much manual testing by the maintainer to verify the functionality of the package.
If there are existing tests for the package, they should be run to verify your changes do not break the tests.
Tests only apply to packages with NixOS modules defined and can only be run on Linux.
For more details on writing and running tests, see the https://nixos.org/nixos/manual/index.html#sec-nixos-tests[section in the NixOS manual]. 

[[_submitting_changes_tested_compilation]]
=== Tested compilation of all pkgs that depend on this change using [command]``nixpkgs-review``


If you are updating a package's version, you can use nixpkgs-review to make sure all packages that depend on the updated package still compile correctly.
The [command]``nixpkgs-review`` utility can look for and build all dependencies either based on uncommited changes with the `wip` option or specifying a github pull request number. 

review changes from pull request number 12345: 
----
nix run nixpkgs.nixpkgs-review -c nixpkgs-review pr 12345
----

review uncommitted changes: 
----
nix run nixpkgs.nixpkgs-review -c nixpkgs-review wip
----

review changes from last commit: 
----
nix run nixpkgs.nixpkgs-review -c nixpkgs-review rev HEAD
----

[[_submitting_changes_tested_execution]]
=== Tested execution of all binary files (usually in [path]``./result/bin/`` )


It's important to test any executables generated by a build when you change or create a package in nixpkgs.
This can be done by looking in [path]``./result/bin``
 and running any files in there, or at a minimum, the main executable for the package.
For example, if you make a change to [package]#texlive#
, you probably would only check the binaries associated with the change you made rather than testing all of them. 

[[_submitting_changes_contribution_standards]]
=== Meets Nixpkgs contribution standards


The last checkbox is fits https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md[CONTRIBUTING.md].
The contributing document has detailed information on standards the Nix community has for commit messages, reviews, licensing of contributions you make to the project, etc... Everyone should read and understand the standards the community has for contributing before submitting a pull request. 

[[_submitting_changes_hotfixing_pull_requests]]
== Hotfixing pull requests

* Make the appropriate changes in you branch. 
* Don't create additional commits, do 
+
** [command]``git rebase -i``
** [command]``git push --force`` to your branch. 


[[_submitting_changes_commit_policy]]
== Commit policy

* Commits must be sufficiently tested before being merged, both for the master and staging branches. 
* Hydra builds for master and staging should not be used as testing platform, it's a build farm for changes that have been already tested. 
* When changing the bootloader installation process, extra care must be taken. Grub installations cannot be rolled back, hence changes may break people's installations forever. For any non-trivial change to the bootloader please file a PR asking for review, especially from @edolstra. 


[[_submitting_changes_master_branch]]
=== Master branch


The `master` branch is the main development branch.
It should only see non-breaking commits that do not cause mass rebuilds. 

[[_submitting_changes_staging_branch]]
=== Staging branch


The `staging` branch is a development branch where mass-rebuilds go.
It should only see non-breaking mass-rebuild commits.
That means it is not to be used for testing, and changes must have been well tested already.
If the branch is already in a broken state, please refrain from adding extra new breakages. 

[[_submitting_changes_staging_next_branch]]
=== Staging-next branch


The `staging-next` branch is for stabilizing mass-rebuilds submitted to the `staging` branch prior to merging them into ``master``.
Mass-rebuilds should go via the `staging` branch.
It should only see non-breaking commits that are fixing issues blocking it from being merged into the `master ` branch. 

If the branch is already in a broken state, please refrain from adding extra new breakages.
Stabilize it for a few days and then merge into master. 

[[_submitting_changes_stable_release_branches]]
=== Stable release branches

* If you're cherry-picking a commit to a stable release branch ("`backporting`"), always use [command]``git cherry-pick -xe`` and ensure the message contains a clear description about why this needs to be included in the stable branch. 
+ 
An example of a cherry-picked commit would look like this: 
+

----
nixos: Refactor the world.

The original commit message describing the reason why the world was torn apart.

(cherry picked from commit abcdef)
Reason: I just had a gut feeling that this would also be wanted by people from
the stone age.
----
