name: Evaluation checks

on:
  workflow_dispatch:
  push:
    branches:
     - master

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v23
    - run: nix-build ./. -A nix-eval-jobs
    - run: ./result/bin/nix-eval-jobs --workers 1 ./outpaths.nix --arg checkMeta true > outpaths.json
